-- onariam-sync: reset and recreate public schema + Realtime authorization
-- Safe to re-run: drops app-owned objects before recreating them.

-- ---------------------------------------------------------------------------
-- Teardown (tables first — DROP POLICY requires the table to exist)
-- ---------------------------------------------------------------------------

drop table if exists public.rooms_users cascade;
drop table if exists public.profiles cascade;
drop table if exists public.rooms cascade;

drop policy if exists "onariam_authenticated_receive_broadcast_presence" on realtime.messages;
drop policy if exists "onariam_authenticated_send_broadcast_presence" on realtime.messages;
drop policy if exists "onariam_anon_receive_broadcast_presence" on realtime.messages;
drop policy if exists "onariam_anon_send_broadcast_presence" on realtime.messages;

-- ---------------------------------------------------------------------------
-- Public tables (matches Supabase Realtime Cursor authorization examples)
-- ---------------------------------------------------------------------------

create table public.rooms (
  id bigint generated by default as identity primary key,
  topic text not null unique,
  title text,
  created_at timestamptz not null default timezone('utc', now())
);

create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  display_name text,
  email text,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (id)
);

create table public.rooms_users (
  user_id uuid not null references auth.users (id) on delete cascade,
  room_topic text not null references public.rooms (topic) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, room_topic)
);

grant select on public.rooms to anon, authenticated;
grant select on public.profiles to anon, authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, delete on public.rooms_users to authenticated;

alter table public.rooms enable row level security;
alter table public.profiles enable row level security;
alter table public.rooms_users enable row level security;

-- Rooms: anyone can read; authenticated users can manage
create policy "onariam_rooms_select"
  on public.rooms
  for select
  to anon, authenticated
  using (true);

create policy "onariam_rooms_insert"
  on public.rooms
  for insert
  to authenticated
  with check (true);

create policy "onariam_rooms_update"
  on public.rooms
  for update
  to authenticated
  using (true)
  with check (true);

create policy "onariam_rooms_delete"
  on public.rooms
  for delete
  to authenticated
  using (true);

-- Profiles: users manage their own row
create policy "onariam_profiles_select"
  on public.profiles
  for select
  to anon, authenticated
  using (true);

create policy "onariam_profiles_insert"
  on public.profiles
  for insert
  to authenticated
  with check ((select auth.uid()) = id);

create policy "onariam_profiles_update"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "onariam_profiles_delete"
  on public.profiles
  for delete
  to authenticated
  using ((select auth.uid()) = id);

-- Room membership
create policy "onariam_rooms_users_select"
  on public.rooms_users
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "onariam_rooms_users_insert"
  on public.rooms_users
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "onariam_rooms_users_delete"
  on public.rooms_users
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- ---------------------------------------------------------------------------
-- Realtime authorization (broadcast + presence for cursor sharing)
-- ---------------------------------------------------------------------------
-- For private channels: set config.private = true on supabase.channel().
-- For the current demo (public channels), also allow anon below.

create policy "onariam_authenticated_receive_broadcast_presence"
  on realtime.messages
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.rooms_users
      where
        user_id = (select auth.uid())
        and room_topic = (select realtime.topic())
    )
    and realtime.messages.extension in ('broadcast', 'presence')
  );

create policy "onariam_authenticated_send_broadcast_presence"
  on realtime.messages
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.rooms_users
      where
        user_id = (select auth.uid())
        and room_topic = (select realtime.topic())
    )
    and realtime.messages.extension in ('broadcast', 'presence')
  );

-- Open access for anonymous guests (matches default RealtimeCursors demo)
create policy "onariam_anon_receive_broadcast_presence"
  on realtime.messages
  for select
  to anon
  using (realtime.messages.extension in ('broadcast', 'presence'));

create policy "onariam_anon_send_broadcast_presence"
  on realtime.messages
  for insert
  to anon
  with check (realtime.messages.extension in ('broadcast', 'presence'));

-- ---------------------------------------------------------------------------
-- Seed default room used by the Next.js app
-- ---------------------------------------------------------------------------

insert into public.rooms (topic, title)
values ('onariam-sync', 'Onariam Sync')
on conflict (topic) do update set title = excluded.title;
